<?php

if (file_exists(__DIR__ . '/../../../local/settings.local.php')) {
  include __DIR__ . '/../../../local/settings.local.php';
}

// Generated by Wodby.
if (file_exists('/var/www/conf/wodby.settings.php')) {
  include '/var/www/conf/wodby.settings.php';
}

$settings['install_profile'] = 'lightning';
